/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2022-01-25 20:57:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.flaviodev.orm_web.provider.ControllerSession;
import org.hibernate.Session;
import helpers.HibernateUtil;
import org.hibernate.SessionFactory;
import models.Film;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("helpers.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("com.flaviodev.orm_web.provider.ControllerSession");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("models.Film");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    Session sessionH = sessionFactory.openSession();

    ArrayList<Film> all_films_searched = new ArrayList<>();
    ArrayList<Film> all_films_by_term = new ArrayList<>();

    if (session.getAttribute("films_list") != null) {
        all_films_by_term = (ArrayList<Film>) session.getAttribute("films_list");
        session.removeAttribute("films_list");
    }

    all_films_searched = ControllerSession.getAllMovies(sessionH);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <title>Sakila</title>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/home.css\">\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n");
      out.write("              integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">Sakila</a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\n");
      out.write("                        aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("                    <ul class=\"navbar-nav\">\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"index.jsp\">Home</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"nav-item\">\n");
      out.write("                            <a class=\"nav-link active\" aria-current=\"page\" href=\"./pages/create.jsp\">Crear</a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- Search Bar -->\n");
      out.write("        <section class=\"container-fluid mt-5 search-bar mb-5\">\n");
      out.write("            <div class=\"lead mb-3\">Busca todo lo que quieras y crea tu lista de peliculas favoritas !!!</div>\n");
      out.write("            <div class=\"container-search\">\n");
      out.write("                <!-- Dropdown Genre Movies -->\n");
      out.write("                <select name=\"filter_searched\" id=\"filter_search\" class=\"menu-genres btn btn-outline-dark dropdown-toggle\">\n");
      out.write("                    <option selected value=\"0\">Fitrar Género</option>\n");
      out.write("                    <option value=\"1\">Nombre</option>\n");
      out.write("                    <option value=\"2\">Descripcion</option>\n");
      out.write("                    <option value=\"3\">Rating</option>\n");
      out.write("                </select>\n");
      out.write("                <!-- Form -->\n");
      out.write("                <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getDataMovies\" class=\"form-search\" autocomplete=\"off\">\n");
      out.write("                    <input type=\"hidden\" name=\"filter_searched\" id=\"value_selected\">\n");
      out.write("                    <input class=\"form-control text-secondary\" id=\"input_search\" type=\"search\" placeholder=\"Buscar...\" aria-label=\"Search\"\n");
      out.write("                           name=\"query\">\n");
      out.write("                    <button type=\"submit\" id=\"btn-search\" class=\"btn btn-outline-dark\" >Buscar</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <!-- Aquí insertaremos la pelicula que busquen -->\n");
      out.write("        ");

            if (!all_films_by_term.isEmpty()) {
        
      out.write("\n");
      out.write("        <div class=\"wrapper\">\n");
      out.write("            <div class=\"container-movies\">\n");
      out.write("                ");

                    for (Film film : all_films_by_term) {
                
      out.write("\n");
      out.write("                <!-- Cards Created -->\n");
      out.write("                <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("                    <div class=\"card-header bg-secondary text-white\">\n");
      out.write("                        <h5 class=\"card-title\">");
      out.print(film.getTitle());
      out.write("</h5>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <p class=\"card-subtitle\">");
      out.print(film.getDescription());
      out.write("</p>\n");
      out.write("                        <p class=\"card-text mt-3\"><b>Clasificación: </b>");
      out.print(film.getRating());
      out.write("</p>\n");
      out.write("                        <p class=\"card-text\"><b>Año de realización: </b>");
      out.print(film.getReleaseYear());
      out.write("</p>\n");
      out.write("                        <div class=\"card-footer\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/updateFilm?id_movie=");
      out.print(film.getFilmId());
      out.write("\" class=\"btn btn-secondary\">Editar</a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteFilm?id_movie=");
      out.print(film.getFilmId());
      out.write("\" class=\"btn btn-danger\">Eliminar</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
 } else {
      out.write("\n");
      out.write("\n");
      out.write("        ");

            if (!all_films_searched.isEmpty()) {
        
      out.write("\n");
      out.write("        <div class=\"wrapper\">\n");
      out.write("            <div class=\"container-movies\">\n");
      out.write("                ");

                    for (Film film : all_films_searched) {

                
      out.write("\n");
      out.write("                <!-- Cards Created -->\n");
      out.write("                <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("                    <div class=\"card-header bg-secondary text-white\">\n");
      out.write("                        <h5 class=\"card-title\">");
      out.print(film.getTitle());
      out.write("</h5>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <p class=\"card-subtitle\">");
      out.print(film.getDescription());
      out.write("</p>\n");
      out.write("                        <p class=\"card-text mt-3\"><b>Clasificación: </b>");
      out.print(film.getRating());
      out.write("</p>\n");
      out.write("                        <p class=\"card-text\"><b>Año de realización: </b>");
      out.print(film.getReleaseYear());
      out.write("</p>\n");
      out.write("                        <div class=\"card-footer\">\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/updateFilm?id_movie=");
      out.print(film.getFilmId());
      out.write("\" class=\"btn btn-secondary\">Editar</a>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/deleteFilm?id_movie=");
      out.print(film.getFilmId());
      out.write("\" class=\"btn btn-danger\">Eliminar</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("                ");
 } else {
      out.write("\n");
      out.write("                <p>Realiza una busqueda!!!</p>\n");
      out.write("                ");
}

                    }
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("                integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\n");
      out.write("        crossorigin=\"anonymous\"></script>\n");
      out.write("        <script>\n");
      out.write("            const options = document.querySelector('#filter_search')\n");
      out.write("            const btn_create = document.querySelector('#btn-search')\n");
      out.write("            const input = document.querySelector('#value_selected')\n");
      out.write("\n");
      out.write("\n");
      out.write("            //Función que al cargar desactiva el boton de busqueda para evitar que el usuario haga una busqueda sin escoge un filtro\n");
      out.write("            window.addEventListener('load', function () {\n");
      out.write("                if (options.children[0].value === '0') {\n");
      out.write("                    btn_create.setAttribute('disabled', '')\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("\n");
      out.write("\n");
      out.write("            //Aqui activamos o descativamos el boton de busqueda si se selecciona un campo valido\n");
      out.write("            options.addEventListener('change', function (e) {\n");
      out.write("                let value_options = e.target.children\n");
      out.write("                let value = value_options[e.target.value].value\n");
      out.write("\n");
      out.write("                if (value != '0') {\n");
      out.write("                    btn_create.removeAttribute('disabled')\n");
      out.write("                    input.value = value\n");
      out.write("                    input.setAttribute('value',value)\n");
      out.write("\n");
      out.write("                } else {\n");
      out.write("                    btn_create.setAttribute('disabled', '')\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
