/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-03 04:11:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

import modelos.Usuario;

public final class cuentaRegistrada_jsp extends org.apache.jasper.runtime.HttpJspBase
        implements org.apache.jasper.runtime.JspSourceDependent,
        org.apache.jasper.runtime.JspSourceImports {

    private static final javax.servlet.jsp.JspFactory _jspxFactory =
            javax.servlet.jsp.JspFactory.getDefaultFactory();

    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    private static final java.util.Set<java.lang.String> _jspx_imports_packages;

    private static final java.util.Set<java.lang.String> _jspx_imports_classes;

    static {
        _jspx_imports_packages = new java.util.HashSet<>();
        _jspx_imports_packages.add("javax.servlet");
        _jspx_imports_packages.add("javax.servlet.http");
        _jspx_imports_packages.add("javax.servlet.jsp");
        _jspx_imports_classes = new java.util.HashSet<>();
        _jspx_imports_classes.add("modelos.Usuario");
    }

    private volatile javax.el.ExpressionFactory _el_expressionfactory;
    private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
        return _jspx_dependants;
    }

    public java.util.Set<java.lang.String> getPackageImports() {
        return _jspx_imports_packages;
    }

    public java.util.Set<java.lang.String> getClassImports() {
        return _jspx_imports_classes;
    }

    public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
        if (_el_expressionfactory == null) {
            synchronized (this) {
                if (_el_expressionfactory == null) {
                    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
                }
            }
        }
        return _el_expressionfactory;
    }

    public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
        if (_jsp_instancemanager == null) {
            synchronized (this) {
                if (_jsp_instancemanager == null) {
                    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
                }
            }
        }
        return _jsp_instancemanager;
    }

    public void _jspInit() {
    }

    public void _jspDestroy() {
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException {

        final java.lang.String _jspx_method = request.getMethod();
        if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
            response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
            return;
        }

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session = null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out = null;
        final java.lang.Object page = this;
        javax.servlet.jsp.JspWriter _jspx_out = null;
        javax.servlet.jsp.PageContext _jspx_page_context = null;


        try {
            response.setContentType("text/html;charset=UTF-8");
            pageContext = _jspxFactory.getPageContext(this, request, response,
                    null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;

            out.write("\n");
            out.write("\n");
            out.write("\n");
            out.write("\n");
            out.write("<!DOCTYPE html>\n");

            Usuario user = (Usuario) session.getAttribute("user");
            String token = (String) session.getAttribute("token");
            if (user == null) {
                session.setAttribute("error", "Debes de loguearte.");
                response.sendRedirect("pages/error.jsp");
            } else {

                out.write("\n");
                out.write("<html lang=\"en\">\n");
                out.write("  <head>\n");
                out.write("    <meta charset=\"UTF-8\" />\n");
                out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
                out.write("    <title>FernanPop</title>\n");
                out.write("    <!--Styles css-->\n");
                out.write("    <!-- <link rel=\"stylesheet\" href=\"http://carlosprofe.es/email.css\"> -->\n");
                out.write("    <link rel=\"stylesheet\" href=\"../css/email.css\" />\n");
                out.write("    <!--fonts -->\n");
                out.write("    <link\n");
                out.write("      href=\"https://fonts.googleapis.com/css2?family=Quicksand:wght@500;700&family=Raleway:wght@700;900&display=swap\"\n");
                out.write("      rel=\"stylesheet\"\n");
                out.write("    />\n");
                out.write("    <!--fontawesome icons-->\n");
                out.write("    <link\n");
                out.write("      rel=\"stylesheet\"\n");
                out.write("      href=\"https://use.fontawesome.com/releases/v5.15.1/css/all.css\"\n");
                out.write("      integrity=\"sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp\"\n");
                out.write("      crossorigin=\"anonymous\"\n");
                out.write("    />\n");
                out.write("  </head>\n");
                out.write("  <body>\n");
                out.write("    <div class=\"container\">\n");
                out.write("      <h1 class=\"title\">\n");
                out.write("        <a href=\"https://flaviooria.github.io/FernanPop-web/\" target=\"_blank\"\n");
                out.write("          >FernanPop</a\n");
                out.write("        >\n");
                out.write("      </h1>\n");
                out.write("      <div class=\"container-home\">\n");
                out.write("        <div class=\"home-welcome\">\n");
                out.write("          <h3 class=\"title-home\">Bienvenido!!!</h3>\n");
                out.write("          <p>\n");
                out.write("              Hola ");
                out.print(user.getNombre());
                out.write(",<br />Para terminar de configurar tu cuenta y empezar a\n");
                out.write("            usar FernanPop, confirma que te has registrado correctamente.\n");
                out.write("          </p>\n");
                out.write("        </div>\n");
                out.write("        <hr />\n");
                out.write("        <div class=\"token-validation\">\n");
                out.write("          <p>Copia el siguiente token para validarte.</p>\n");
                out.write("          <div class=\"token\">\n");
                out.write("            <p>\n");
                out.write("              token: <span id=\"token\">");
                out.print(token);
                out.write("</span\n");
                out.write("              ><i class=\"fas fa-copy\" title=\"copiar\"></i>\n");
                out.write("            </p>\n");
                out.write("          </div>\n");
                out.write("        </div>\n");
                out.write("        <hr />\n");
                out.write("        <div class=\"slogan-web\">\n");
                out.write("          <p>Tus amigos de FernanPop <i class=\"fas fa-heart\"></i></p>\n");
                out.write("          <div>\n");
                out.write("          <a class=\"home\" href=\"./inicio.jsp\">Da click aquí para continuar</a>\n");
                out.write("        </div>\n");
                out.write("        </div>\n");
                out.write("      </div>\n");
                out.write("      <div class=\"footer\">\n");
                out.write("        <p>© 2021 FernanPop Web - Martos, Jaén, España</p>\n");
                out.write("        <ul class=\"about-media\">\n");
                out.write("          <li>\n");
                out.write("            <a href=\"\" title=\"facebook/fernanpop.com\"\n");
                out.write("              ><i class=\"fab fa-facebook-square\"></i\n");
                out.write("            ></a>\n");
                out.write("          </li>\n");
                out.write("          <li>\n");
                out.write("            <a href=\"\"><i class=\"fab fa-instagram-square\"></i></a>\n");
                out.write("          </li>\n");
                out.write("          <li>\n");
                out.write("            <a href=\"\"><i class=\"fab fa-twitter-square\"></i></a>\n");
                out.write("          </li>\n");
                out.write("          <li>\n");
                out.write("            <a\n");
                out.write("              href=\"https://github.com/flaviooria/FernanPop-web\"\n");
                out.write("              target=\"_blank\"\n");
                out.write("              ><i class=\"fab fa-github-square\"></i\n");
                out.write("            ></a>\n");
                out.write("          </li>\n");
                out.write("        </ul>\n");
                out.write("      </div>\n");
                out.write("    </div>\n");
                out.write("  </body>\n");
                out.write("  ");
            }
            out.write("\n");
            out.write(" <!-- <script src=\"../js/email.js\"></script>-->\n");
            out.write("</html>\n");
            out.write("\n");
        } catch (java.lang.Throwable t) {
            if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0)
                    try {
                        if (response.isCommitted()) {
                            out.flush();
                        } else {
                            out.clearBuffer();
                        }
                    } catch (java.io.IOException e) {
                    }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
