/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-03 04:11:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
        implements org.apache.jasper.runtime.JspSourceDependent,
        org.apache.jasper.runtime.JspSourceImports {

    private static final javax.servlet.jsp.JspFactory _jspxFactory =
            javax.servlet.jsp.JspFactory.getDefaultFactory();

    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    private static final java.util.Set<java.lang.String> _jspx_imports_packages;

    private static final java.util.Set<java.lang.String> _jspx_imports_classes;

    static {
        _jspx_imports_packages = new java.util.HashSet<>();
        _jspx_imports_packages.add("javax.servlet");
        _jspx_imports_packages.add("javax.servlet.http");
        _jspx_imports_packages.add("javax.servlet.jsp");
        _jspx_imports_classes = null;
    }

    private volatile javax.el.ExpressionFactory _el_expressionfactory;
    private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
        return _jspx_dependants;
    }

    public java.util.Set<java.lang.String> getPackageImports() {
        return _jspx_imports_packages;
    }

    public java.util.Set<java.lang.String> getClassImports() {
        return _jspx_imports_classes;
    }

    public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
        if (_el_expressionfactory == null) {
            synchronized (this) {
                if (_el_expressionfactory == null) {
                    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
                }
            }
        }
        return _el_expressionfactory;
    }

    public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
        if (_jsp_instancemanager == null) {
            synchronized (this) {
                if (_jsp_instancemanager == null) {
                    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
                }
            }
        }
        return _jsp_instancemanager;
    }

    public void _jspInit() {
    }

    public void _jspDestroy() {
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException {

        final java.lang.String _jspx_method = request.getMethod();
        if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
            response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
            return;
        }

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session = null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out = null;
        final java.lang.Object page = this;
        javax.servlet.jsp.JspWriter _jspx_out = null;
        javax.servlet.jsp.PageContext _jspx_page_context = null;


        try {
            response.setContentType("text/html;charset=UTF-8");
            pageContext = _jspxFactory.getPageContext(this, request, response,
                    null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;

            out.write("\n");
            out.write("\n");
            out.write("<!DOCTYPE html>\n");
            out.write("<html lang=\"en\">\n");
            out.write("\n");
            out.write("<head>\n");
            out.write("    <meta charset=\"UTF-8\" />\n");
            out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
            out.write("    <title>FernanPop | Logeo</title>\n");
            out.write("    <!--styles css-->\n");
            out.write("    <link rel=\"stylesheet\" href=\"../css/main.css\" />\n");
            out.write("    <!--fonts -->\n");
            out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\n");
            out.write("    <link\n");
            out.write("            href=\"https://fonts.googleapis.com/css2?family=Quicksand:wght@500;700&family=Raleway:wght@700;900&display=swap\"\n");
            out.write("            rel=\"stylesheet\">\n");
            out.write("    <!--fontawesome icons-->\n");
            out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.1/css/all.css\"\n");
            out.write("          integrity=\"sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp\" crossorigin=\"anonymous\" />\n");
            out.write("    <!--Animations CDN-->\n");
            out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\" />\n");
            out.write("    <!--Animation AOS Scroll-->\n");
            out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/aos@next/dist/aos.css\" />\n");
            out.write("</head>\n");
            out.write("\n");
            out.write("<body>\n");
            out.write("<header id=\"inicio\">\n");
            out.write("    <div class=\"hero\">\n");
            out.write("        <div class=\"header animate__animated animate__fadeInLeftBig animate__fast\">\n");
            out.write("            <div class=\"header-navbar\">\n");
            out.write("                <ul class=\"navbar-links\">\n");
            out.write("                    <li><a href=\"#caracteristicas\">Caracteristicas</a></li>\n");
            out.write("                    <li><a href=\"#faqs\">Faqs</a></li>\n");
            out.write("                    <li><a href=\"#contacto\">Contacto</a></li>\n");
            out.write("                </ul>\n");
            out.write("            </div>\n");
            out.write("            <form action=\"\" autocomplete=\"off\">\n");
            out.write("                <div class=\"header-search\">\n");
            out.write("                    <input type=\"text\" name=\"nameProduct\" id=\"nameProduct\" placeholder=\"Busca todo lo que quieras\">\n");
            out.write("                    <button type=\"submit\" class=\"btn-search\"><i class=\"fas fa-search\"></i></button>\n");
            out.write("                </div>\n");
            out.write("            </form>\n");
            out.write("        </div>\n");
            out.write("        <div class=\"hero-title animate__animated animate__fadeIn animate__slower animate-delay-3s\">\n");
            out.write("            <h1>Fernan<span class=\"orange\">Pop</span></h1>\n");
            out.write("            <p>Vende y compra lo que quieras en cualquier momento y lugar.</p>\n");
            out.write("        </div>\n");
            out.write("        <div class=\"hero-register animate__animated animate__fadeIn animate__slower animate-delay-3s\">\n");
            out.write("            <form id=\"form-login\" method=\"post\" action=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("/verifyLogin\">\n");
            out.write("                <h3>Inciar Sesión</h3>\n");
            out.write("                <label for=\"correo\">Correo electronico:</label><br />\n");
            out.write("                <input type=\"email\" name=\"email\" id=\"correo\" /><br />\n");
            out.write("                <label for=\"password\">Contraseña:</label><br />\n");
            out.write("                <input type=\"password\" name=\"pass\" id=\"password\">\n");
            out.write("                <div class=\"password\">\n");
            out.write("                    <input type=\"checkbox\" class=\"checkbox\">Mostrar contraseña\n");
            out.write("                </div>\n");
            out.write("                <div class=\"spinner\">\n");
            out.write("                    <div class=\"double-bounce1\"></div>\n");
            out.write("                    <div class=\"double-bounce2\"></div>\n");
            out.write("                </div>\n");
            out.write("                ");

            boolean failed = Boolean.parseBoolean((String) session.getAttribute("failed"));
            System.out.println(failed);
            if (failed) {

                out.write("\n");
                out.write("                <p>No se pudo iniciar sesión, intentalo de nuevo.</p>\n");
                out.write("                ");
            }
            out.write("\n");
            out.write("                <button class=\"send\" type=\"submit\">Entrar <i class=\"fas fa-chevron-right\"></i></button>\n");
            out.write("            </form>\n");
            out.write("        </div>\n");
            out.write("        <div class=\"wave-bottom\" style=\"height: 150px; overflow: hidden;\"><svg viewBox=\"0 0 500 150\"\n");
            out.write("                                                                               preserveAspectRatio=\"none\" style=\"height: 100%; width: 100%;\">\n");
            out.write("            <path d=\"M0.00,49.98 C323.64,137.66 206.83,-33.05 500.00,49.98 L504.79,112.00 L-3.10,107.06 Z\"\n");
            out.write("                  style=\"stroke: none; \"></path>\n");
            out.write("        </svg></div>\n");
            out.write("    </div>\n");
            out.write("</header>\n");
            out.write("<section id=\"caracteristicas\">\n");
            out.write("    <div class=\"features\" data-aos=\"zoom-in\" data-aos-easing=\"ease\">\n");
            out.write("        <h3>Caracteristicas</h3>\n");
            out.write("        <div class=\"features-items\">\n");
            out.write("            <div class=\"item-badge\">\n");
            out.write("                <img src=\"../assets/img/soFast-trust.png\" width=\"250\" alt=\"rapido-confiable\" />\n");
            out.write("                <p>Es rapido y confiable.</p>\n");
            out.write("            </div>\n");
            out.write("            <div class=\"item-badge\">\n");
            out.write("                <img src=\"../assets/img/pay-secure.png\" width=\"250\" alt=\"pagoSeguro\" />\n");
            out.write("                <p>Pagos seguros siempre.</p>\n");
            out.write("            </div>\n");
            out.write("            <div class=\"item-badge\">\n");
            out.write("                <img src=\"../assets/img/succes.png\" width=\"250\" alt=\"acuerdo-mutuo\" />\n");
            out.write("                <p>\n");
            out.write("                    Acuerdo mutuo entre<br>comprador\n");
            out.write("                    y vendedor.\n");
            out.write("                </p>\n");
            out.write("            </div>\n");
            out.write("        </div>\n");
            out.write("    </div>\n");
            out.write("</section>\n");
            out.write("<section id=\"faqs\">\n");
            out.write("    <div class=\"faqs\">\n");
            out.write("        <div class=\"faqs-wave-top\" style=\"height: 130px; overflow: hidden;\"><svg viewBox=\"0 0 500 150\"\n");
            out.write("                                                                                 preserveAspectRatio=\"none\" style=\"height: 100%; width: 100%;\">\n");
            out.write("            <path d=\"M0.00,49.98 C149.99,150.00 271.49,-49.98 500.00,49.98 L500.00,0.00 L0.00,0.00 Z\"\n");
            out.write("                  style=\"stroke: none;\"></path>\n");
            out.write("        </svg></div>\n");
            out.write("        <div class=\"faqs-logo\" data-aos=\"fade-in\" data-aos-easing=\"ease\">\n");
            out.write("            <img src=\"../assets/img/faq.jpg\" width=\"500\" alt=\"\">\n");
            out.write("        </div>\n");
            out.write("        <div class=\"faqs-list\" data-aos=\"fade-in\" data-aos-easing=\"ease\">\n");
            out.write("            <h1>Preguntas Frecuentes</h1>\n");
            out.write("            <p class=\"question\">¿Puedó pagar con distintas entidades, incluyendo PayPal?</p>\n");
            out.write("            <p class=\"response\"> - Claro sí puedes, nuestra app tiene trato directo con entidades financieras para\n");
            out.write("                hacer tus pagos seguros.</p>\n");
            out.write("            <p class=\"question\">¿Las compras y ventas se puede hacer en toda españa?</p>\n");
            out.write("            <p class=\"response\"> - Nuestros servicios de compra y venta funciona alreddor de toda la Union Europea.\n");
            out.write("            </p>\n");
            out.write("            <p class=\"question\">¿Es fernanpop la mejor app de venta y compra?</p>\n");
            out.write("            <p class=\"response\"> - Definitivamente Sí !!!</p>\n");
            out.write("        </div>\n");
            out.write("        <div class=\"faqs-wave-bottom\" style=\"height: 130px; overflow: hidden;\"><svg viewBox=\"0 0 500 150\"\n");
            out.write("                                                                                    preserveAspectRatio=\"none\" style=\"height: 100%; width: 100%;\">\n");
            out.write("            <path d=\"M-21.72,16.28 C192.71,110.03 294.86,103.13 518.90,14.30 L500.00,150.00 L0.00,150.00 Z\"\n");
            out.write("                  style=\"stroke: none;\"></path>\n");
            out.write("        </svg></div>\n");
            out.write("    </div>\n");
            out.write("</section>\n");
            out.write("<section id=\"contacto\">\n");
            out.write("    <div class=\"contact\" data-aos=\"fade-in\" data-aos-easing=\"ease\">\n");
            out.write("        <h1>¿Necesitas ayuda? <br> <span>Contactanos</span> </h1>\n");
            out.write("\n");
            out.write("        <div class=\"contact-info\">\n");
            out.write("            <form action=\"\">\n");
            out.write("                <label for=\"\">Correo:</label>\n");
            out.write("                <input type=\"email\" name=\"\" id=\"txtEmail\">\n");
            out.write("                <label for=\"\">Indica cual es tu problema o consulta:</label>\n");
            out.write("                <textarea name=\"\" id=\"txtAreaConsulta\" cols=\"30\" rows=\"10\"></textarea>\n");
            out.write("                <button>Enviar <i class=\"fas fa-envelope-open-text\"></i></button>\n");
            out.write("            </form>\n");
            out.write("        </div>\n");
            out.write("    </div>\n");
            out.write("</section>\n");
            out.write("<footer id=\"Acerca\">\n");
            out.write("    <div class=\"about-wave-top\" style=\"height: 100px; overflow: hidden;\"><svg viewBox=\"0 0 500 150\"\n");
            out.write("                                                                              preserveAspectRatio=\"none\" style=\"height: 100%; width: 100%;\">\n");
            out.write("        <path d=\"M-0.84,36.02 C207.38,99.17 272.85,100.16 503.10,28.13 L500.00,0.00 L0.00,0.00 Z\"\n");
            out.write("              style=\"stroke: none;\"></path>\n");
            out.write("    </svg></div>\n");
            out.write("    <div class=\"about\" ata-aos=\"fade-in\" data-aos-easing=\"ease\">\n");
            out.write("        <p>Derechos Reservados ©</p>\n");
            out.write("        <p>Diseñado por <span class=\"orange\">@FlavioOria</span></p>\n");
            out.write("        <ul class=\"about-media\">\n");
            out.write("            <li><a href=\"\" title=\"facebook/fernanpop.com\"><i class=\"fab fa-facebook-square\"></i></a></li>\n");
            out.write("            <li><a href=\"\"><i class=\"fab fa-instagram-square\"></i></a></li>\n");
            out.write("            <li><a href=\"\"><i class=\"fab fa-twitter-square\"></i></a></li>\n");
            out.write("            <li><a class=\"inicio\" href=\"#inicio\" title=\"Inicio\"><i class=\"fas fa-arrow-circle-up\"></i></a></li>\n");
            out.write("        </ul>\n");
            out.write("    </div>\n");
            out.write("</footer>\n");
            out.write("</body>\n");
            out.write("<!--Script de animation scroll-->\n");
            out.write("<script src=\"https://unpkg.com/aos@next/dist/aos.js\"></script>\n");
            out.write("<script src=\"../js/loger.js\"></script>\n");
            out.write("</html>");
        } catch (java.lang.Throwable t) {
            if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0)
                    try {
                        if (response.isCommitted()) {
                            out.flush();
                        } else {
                            out.clearBuffer();
                        }
                    } catch (java.io.IOException e) {
                    }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
